### PR TITLE
Clientless pom

### LINKED ISSUE #4: Parse a Pom from a plain pom file path
The constructor of Pom is restricted because it assumes that I must know "coordinates" ahead of time https://github.com/sassoftware/pymaven/blob/3a844cd3dc10c04196ad12cdf500dde233f5a508/pymaven/pom.py#L49
And that I have effectively some repo that handles the retrieval. In my usecase for ScanCode as a possible replacement of this https://github.com/nexB/scancode-toolkit/blob/develop/src/packagedcode/maven.py I need to be able to parse a POM from some file path and nothing else. I do not have a "repo" nor do I know the "coordinates" yet: the whole purpose of parsing for me is to discover these....

So I am left with this alternative:
1. beef up pymaven with extra effort to find a way to keep your initial use case assumptions. But I do not know enough about this.
2. fork and add my features: along the way I would likely be breaking your assumptions and support for your use case.

I hate 2. but I cannot see a way around this? @wfscheper what do you think?

### PR DESCRIPTION
**Pull request by wfscheper**
Adds support for using the pymaven Pom object without a maven client.

Fixes #4, #7

### CODE REVIEW

**Comment by wfscheper** [comment]
@pombredanne, do you have any comments or concerns with this implementation before I merge it?

**Comment by pombredanne** [comment]
@wfscheper Thanks ++!
let me review all this. I also still have on my todo to update the patches (and many tests) in my fork on top of this and send a PR your way.

**Comment by pombredanne** [comment]
@wfscheper I guess I had forgotten about this: shame on me! Let me review at last. Thank you!

**Comment by pombredanne** [comment]
@wfscheper this is all good for me. I will rebase any pending things and patches I had on this once you merge it is and will send a PR your way

**Comment by pombredanne** [comment]
Thank you ++

**Pull request merged**
